name: tflite_flutter_helper
description: Easy, fast processing and manipulation input and output of TensorFlow Lite Models.
version: 0.3.0
homepage: https://www.github.com/FutPr0Js/tflite_flutter_helper

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  quiver: ^3.0.1
  path_provider: ^2.0.15
  tflite_flutter: ^0.9.0
  tuple: ^2.0.0
  camera: ^0.11.0+1
  ffi: ^2.0.1
  image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tfliteflutter.tflite_flutter_helper
        pluginClass: TfliteFlutterHelperPlugin
      ios:
        pluginClass: TfliteFlutterHelperPlugin
      linux:
        pluginClass: TfliteFlutterHelperPlugin
      macos:
        pluginClass: TfliteFlutterHelperPlugin
      windows:
        pluginClass: TfliteFlutterHelperPlugin
